// <auto-generated />
using System;
using CatalogoRopaMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogoRopaMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260628213919_AgregarVendedorUnico")]
    partial class AgregarVendedorUnico
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogoRopaMVC.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Playeras casuales y básicas.",
                            Nombre = "Playeras"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Jeans, joggers y pantalones casuales.",
                            Nombre = "Pantalones"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Prendas para frío y outfits urbanos.",
                            Nombre = "Chamarras"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Gorras, bolsas y complementos.",
                            Nombre = "Accesorios"
                        });
                });

            modelBuilder.Entity("CatalogoRopaMVC.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoHex")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Colores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoHex = "#FFFFFF",
                            Nombre = "Blanco"
                        },
                        new
                        {
                            Id = 2,
                            CodigoHex = "#1F5AA6",
                            Nombre = "Azul"
                        },
                        new
                        {
                            Id = 3,
                            CodigoHex = "#111111",
                            Nombre = "Negro"
                        },
                        new
                        {
                            Id = 4,
                            CodigoHex = "#7A4F36",
                            Nombre = "Café"
                        });
                });

            modelBuilder.Entity("CatalogoRopaMVC.Models.ImagenProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("TextoAlternativo")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("ImagenesProducto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EsPrincipal = true,
                            ProductoId = 1,
                            TextoAlternativo = "Playera básica blanca",
                            Url = "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab"
                        },
                        new
                        {
                            Id = 2,
                            EsPrincipal = true,
                            ProductoId = 2,
                            TextoAlternativo = "Jeans azul clásico",
                            Url = "https://images.unsplash.com/photo-1542272604-787c3835535d"
                        },
                        new
                        {
                            Id = 3,
                            EsPrincipal = true,
                            ProductoId = 3,
                            TextoAlternativo = "Chamarra negra urbana",
                            Url = "https://images.unsplash.com/photo-1551028719-00167b16eac5"
                        });
                });

            modelBuilder.Entity("CatalogoRopaMVC.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("TallaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ColorId");

                    b.HasIndex("TallaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            ColorId = 1,
                            Descripcion = "Playera de algodón para uso diario.",
                            Disponible = true,
                            FechaRegistro = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Playera básica blanca",
                            Precio = 199.00m,
                            Stock = 12,
                            TallaId = 3
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            ColorId = 2,
                            Descripcion = "Pantalón de mezclilla para outfit casual.",
                            Disponible = true,
                            FechaRegistro = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Jeans azul clásico",
                            Precio = 549.00m,
                            Stock = 8,
                            TallaId = 6
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            ColorId = 3,
                            Descripcion = "Chamarra ligera para clima fresco.",
                            Disponible = true,
                            FechaRegistro = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Chamarra negra urbana",
                            Precio = 899.00m,
                            Stock = 5,
                            TallaId = 4
                        });
                });

            modelBuilder.Entity("CatalogoRopaMVC.Models.Talla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Tallas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "XS"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "S"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "M"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "L"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "XL"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "32"
                        });
                });

            modelBuilder.Entity("CatalogoRopaMVC.Models.Vendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("EmailNormalizado")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("LlaveUnica")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("VENDEDOR_DUENO");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmailNormalizado")
                        .IsUnique();

                    b.HasIndex("LlaveUnica")
                        .IsUnique();

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("CatalogoRopaMVC.Models.ImagenProducto", b =>
                {
                    b.HasOne("CatalogoRopaMVC.Models.Producto", "Producto")
                        .WithMany("Imagenes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("CatalogoRopaMVC.Models.Producto", b =>
                {
                    b.HasOne("CatalogoRopaMVC.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CatalogoRopaMVC.Models.Color", "Color")
                        .WithMany("Productos")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CatalogoRopaMVC.Models.Talla", "Talla")
                        .WithMany("Productos")
                        .HasForeignKey("TallaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Color");

                    b.Navigation("Talla");
                });

            modelBuilder.Entity("CatalogoRopaMVC.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("CatalogoRopaMVC.Models.Color", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("CatalogoRopaMVC.Models.Producto", b =>
                {
                    b.Navigation("Imagenes");
                });

            modelBuilder.Entity("CatalogoRopaMVC.Models.Talla", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
